sudo: required
services:
  - docker
language: python
python:
  - 3.5
install:
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine
  - sudo pip install docker-compose
before_script:
  - docker version
  - docker-compose --version
script:
  - docker-compose build --pull
  - docker-compose up -d
  - docker-compose exec web py.test
  - docker-compose exec web pylama
  - docker-compose run web pipchecker -r ../requirements.txt
notifications:
  email: false
  slack:
    secure: svF4s449i9Dl8hsdw3KDMfRZCfWIZG42kq4rfXMK1RWd5FugHu4uFV/9c4To9hu6eeeOPmjpLg4Fj25x2djUl4dRdgtMkxQBtxTo5dobuVmCB696NT5oPncWfyApk4QGOg4gzEsq0V6vI+E9ajSXmhn8An5qH/YiMbv8aaczLSRgKAPico+VMMe8KWpsiNo42GkVi2y+HHKCz55H+6QuRSgY9lHym6c8+UdE1T0bToNziEu6iBIZNrZtOFoAtIALK8uxA6AHLHmJYi5gRp+kmnfBMhMD8BXJCEwt0AwxOPM7/viIocjvb0RMzmzU/rAL0jiNNCSTgMv40gcylc4uhnUL30VqXoLs+oF2nMN4G7aBki20PCu7Jhc1UsxbPOqIKsS5rSbpASYGRo689de9fuimd3KcPlL20VA3ysP4144Pqz/0CWTbUusXSF/12ZAFUB+oMvmTJP+fsAsr5OiR0q37A+E3bfHNwhBFGco8m3I7v4Zxl/VeMSeVN+26P73W9hGBuVAyd4zYEWIDuYZy5BP15lzxWKGHo32pymmjhC1K8Gx3nJDgECEEWl+O3KobGQ1cf9Oijp1qVGYrZR7vlx3efPRAqzV8QEDXXSSiaoh0VaRLxJKT7u5yRawCjFyCMoWgibdfjaLjXGg9HfuD6VAkC1iMF168MxdiyVSEjIA=
