version: '2'
services:
    web:
      build: .
      command: "runserver 0.0.0.0:8011"
      environment:
          PYTHONUNBUFFERED: 0
          PYTHONDONTWRITEBYTECODE: 1
          DJANGO_SETTINGS_MODULE: letsmeet.settings.dev
          TOX_WORK_DIR: /opt/tox
      entrypoint:
       - './manage.py'
      volumes:
       - .:/opt/code
       - userhome:/home/uid1000
      ports:
       - "8011:8011"
      depends_on:
       - db

    db:
      image: mdillon/postgis:9.4
      volumes:
       - postgisdata:/var/lib/postgresql/data

volumes:
  userhome:
    driver: local
  postgisdata:
    driver: local
