# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20151230_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='homepage',
            field=models.URLField(blank=True, help_text='URL of homepage (including http://)', max_length=128, null=True),
        ),
    ]
