# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20151227_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='communitysubscription',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='community',
            name='cname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='subscribers',
            field=models.ManyToManyField(related_name='communities', through='communities.CommunitySubscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitysubscription',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_subscriptions', to='communities.Community'),
        ),
        migrations.AlterField(
            model_name='communitysubscription',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('subscriber', 'Subscriber')], default='subscriber', max_length=64),
        ),
        migrations.AlterField(
            model_name='communitysubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='communitysubscription',
            unique_together=set([('community', 'user')]),
        ),
    ]
