# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 03:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20151227_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='github',
            field=models.CharField(blank=True, help_text='GitHub username or organisation name', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='homepage',
            field=models.URLField(blank=True, help_text='URL of homepage (including http://)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='irc_channel',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='irc_network',
            field=models.CharField(blank=True, help_text='Network the IRC channel is located on (e.g. "Freenode")', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='slack',
            field=models.CharField(blank=True, help_text='Slack organisation name', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter username', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='cname',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('/^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\\.[a-zA-Z]{2,}$/')], verbose_name='CNAME'),
        ),
    ]
