# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20151228_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='irc_channel',
            field=models.CharField(blank=True, help_text='IRC channel name', max_length=128, null=True, verbose_name='IRC channel'),
        ),
        migrations.AlterField(
            model_name='community',
            name='irc_network',
            field=models.CharField(blank=True, help_text='Network the IRC channel is located on (e.g. "Freenode")', max_length=128, null=True, verbose_name='IRC network'),
        ),
    ]
