# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 12:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20151228_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='cname',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9-\\.]+')], verbose_name='CNAME'),
        ),
    ]
