# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_auto_20151228_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='cname',
            field=models.CharField(blank=True, help_text='use your own domain to redirect to this community.', max_length=255, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9-\\.\\ ]+')], verbose_name='CNAME'),
        ),
        migrations.AlterField(
            model_name='community',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter username (without leading @)', max_length=128, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9_]+')]),
        ),
    ]
