# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('communities', '0010_auto_20160108_1618'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='community',
            managers=[
            ],
        ),
    ]
