# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_auto_20160318_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, help_text='You can write markown here!', null=True),
        ),
    ]
