# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrsvp',
            options={'ordering': ('-coming', 'user')},
        ),
    ]
