# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20151228_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='changing the slug will change the url.', max_length=64),
        ),
    ]
