# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_twitter_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='decsription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
