# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_decsription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='decsription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='Note: changing the slug will change the URL of the event', max_length=64),
        ),
    ]
