# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0009_auto_20160107_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(
                help_text='Optional maximum number of attendees for this event. Leave blank for no limit.', null=True),
        ),
    ]
