# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_notify_on_new_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_new_subsciption',
            field=models.BooleanField(default=True),
        ),
    ]
