# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_notify_on_new_subsciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='notify_on_new_subsciption',
            new_name='notify_on_new_subscription',
        ),
    ]
