# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160106_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_new_rsvp_for_attending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_new_rsvp_for_organizer',
            field=models.BooleanField(default=True),
        ),
    ]
