# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160107_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_new_comment',
            field=models.BooleanField(default=True),
        ),
    ]
