# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_notify_on_new_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_email_address',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
