# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_pending_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_ical_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
