# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 22:02
from __future__ import unicode_literals

from django.db import migrations, models, transaction
import uuid


def forward(apps, schema_editor):
    UserProfile = apps.get_model("users", "userprofile")
    for up in UserProfile.objects.all():
        with transaction.atomic():
            up.personal_ical_uuid = uuid.uuid4()
            up.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_pending_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_ical_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
